# Google Analytics
googleAnalytics = "UA-219883372-1"
gtagId = "G-61LNEQWN02" 


baseURL = "https://sdavidsson.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Sighvatur S. Davidsson"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
# Enable Disqus
#disqusShortname = ""


# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
displayMode = "light"
disableThemeSwitcher = false 

contentratio = 0.666