
title = "Sighvatur S. Davidsson"
author = "Sighvatur S. Davidsson"
description = """ I do data science. This is my blog. Have a look around!"""

profilePicture = "images/profile.jpg"
keywords = "sighvatur"
favicon = "favicons/"

# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
# images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"


# Google analytics (tilføjet af mig)
gtagId = "G-GYJ2KPEQG5" # også tilføjet af mig

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/sighvatur-s-davidsson-8807aa105/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/sdavidsson90"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:sdavidsson90@outlook.dk"